import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Container from '@/components/Container';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

const uncage = localFont({
  src: '../../public/fonts/uncage.woff',
  variable: '--font-uncage',
});

const anomaly = localFont({
  src: '../../public/fonts/anomaly.woff',
  variable: '--font-anomaly',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${uncage.variable} ${anomaly.variable}`}>
        <div className='relative min-h-screen'>
          {/* Column Background */}
          <div className='absolute inset-0 grid grid-cols-12'>
            {[...Array(12)].map((_, i) => (
              <div
                key={i}
                className='border-l border-gray-300 bg-westar-200 last:border-r'
              />
            ))}
          </div>

          <Navigation />
          {/* Page Content */}
          <div className='relative z-10'>{children}</div>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
